apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flashpaper-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: flashpaper
        image: jmbmxer/flashpaper
        imagePullPolicy: Always
        ports:
        - containerPort: 8443