apiVersion: v1
kind: Service
metadata:
 name: webgoat
 labels:
   app: webgoat
spec:
 ports:
 - name: webgoat
   port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
   app: webgoat
   tier: frontend
 type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webgoat-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webgoat
        tier: frontend
    spec:
      containers:
      - name: webgoat
        image: mrmendes/webgoat-docker
        ports:
        - containerPort: 8080
