apiVersion: v1
kind: Service
metadata:
 name: webgoat
 labels:
   app: webgoat
spec:
 ports:
 - name: webgoat-port
   port: 8080
   protocol: TCP
   targetPort: 8080
 selector:
   app: webgoat
   tier: frontend
 type: LoadBalancer