apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metasploit-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: metasploit
        tier: frontend
    spec:
      containers:
      - name: metasploit
        image: us.gcr.io/unshorten-1306/armitage
        ports:
        - containerPort: 55553