apiVersion: v1
kind: Service
metadata:
 name: metasploit
 labels:
   app: metasploit
spec:
 ports: 
 - name: armitage-ssl
   port: 55553
   protocol: TCP
   targetPort: 55553
 selector:
   app: metasploit
   tier: frontend
 type: LoadBalancer