apiVersion: v1
kind: Service
metadata:
 labels:
   app: zap
 name: security-zap
spec:
 ports:
 - name: zap-web
   port: 8080
   protocol: TCP
   targetPort: 8080
 - name: zap-ui
   port: 8090
   protocol: TCP
   targetPort: 8090
 selector:
   app: zap
 type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zap-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
      - name: zap
        image: owasp/zap2docker-stable
        args: 
        - zap-webswing.sh
        ports:
        - containerPort: 8090

