apiVersion: v1
kind: PersistentVolume
metadata:
  name: threadfix-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: threadfix-1
    fsType: ext4
