apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-threadfix
  labels:
    app: threadfix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi