apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: threadfix-mysql
  labels:
    app: threadfix
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: threadfix
        tier: mysql
    spec:
      containers:
        - resources:
            requests:
              #cpu: 0.1
          image: mysql:5.6
          name: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: threadfix-secrets
                key: threadfix-db-pass
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql-persistent-storage-threadfix
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-threadfix
        persistentVolumeClaim:
          claimName: mysql-pv-claim-threadfix